; Project-maintained Simplified Chinese overrides. Apache-2.0.
; Inno Setup's Default.isl supplies fallback messages for exceptional errors.
[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=936
DialogFontName=Microsoft YaHei UI
DialogFontSize=9
WelcomeFontName=Microsoft YaHei UI
WelcomeFontSize=14

[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载
UninstallAppFullTitle=卸载 %1
InformationTitle=提示
ConfirmTitle=确认
ErrorTitle=错误
SetupLdrStartupMessage=即将安装 %1，是否继续？
SetupFileCorrupt=安装文件损坏，请重新下载安装包。
SetupAlreadyRunning=安装程序已在运行。
WindowsVersionNotSupported=此程序不支持当前 Windows 版本。
OnlyOnTheseArchitectures=此程序仅支持以下处理器架构的 Windows：%n%n%1
SetupAppRunningError=%1 正在运行。%n%n请关闭程序，然后点击“确定”继续安装。
UninstallAppRunningError=%1 正在运行。%n%n请关闭程序，然后点击“确定”继续卸载。
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。现在退出将无法完成安装。%n%n是否退出？
AboutSetupMenuItem=关于安装程序(&A)...
AboutSetupTitle=关于安装程序
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonYesToAll=全部是(&A)
ButtonNo=否(&N)
ButtonNoToAll=全部否(&O)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)...
ButtonWizardBrowse=浏览(&R)...
ButtonNewFolder=新建文件夹(&M)
SelectLanguageTitle=选择安装语言
SelectLanguageLabel=请选择安装向导使用的语言。
ClickNext=点击“下一步”继续，或点击“取消”退出。
BrowseDialogTitle=选择文件夹
BrowseDialogLabel=选择文件夹，然后点击“确定”。
NewFolderName=新建文件夹
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=此向导将在你的电脑上安装 [name/ver]。%n%n建议先关闭正在运行的本程序。
WizardLicense=开源许可证
LicenseLabel=继续安装前，请阅读以下内容。
LicenseLabel3=请阅读以下开源许可证。接受后可继续安装。
LicenseAccepted=我接受协议(&A)
LicenseNotAccepted=我不接受协议(&D)
WizardInfoBefore=说明
InfoBeforeLabel=请阅读以下内容。
InfoBeforeClickLabel=准备好后，点击“下一步”继续。
WizardInfoAfter=说明
InfoAfterLabel=请阅读以下内容。
InfoAfterClickLabel=准备好后，点击“下一步”继续。
WizardSelectDir=选择安装位置
SelectDirDesc=将 [name] 安装到哪里？
SelectDirLabel3=程序将安装到以下文件夹。
SelectDirBrowseLabel=点击“下一步”继续，或点击“浏览”更改安装位置。
DiskSpaceGBLabel=至少需要 [gb] GB 可用磁盘空间。
DiskSpaceMBLabel=至少需要 [mb] MB 可用磁盘空间。
DiskSpaceWarningTitle=磁盘空间不足
DiskSpaceWarning=安装需要至少 %1 KB 空间，但所选磁盘仅有 %2 KB。%n%n是否仍继续？
DirNameTooLong=文件夹名称或路径过长。
InvalidDirName=文件夹名称无效。
DirExistsTitle=文件夹已存在
DirExists=文件夹：%n%n%1%n%n已存在。是否安装到此文件夹？
DirDoesntExistTitle=创建文件夹
DirDoesntExist=文件夹：%n%n%1%n%n尚不存在。是否创建？
WizardSelectTasks=选择附加选项
SelectTasksDesc=需要执行哪些附加操作？
SelectTasksLabel2=选择安装时需要执行的附加操作，然后点击“下一步”。
WizardSelectProgramGroup=开始菜单快捷方式
SelectStartMenuFolderDesc=将快捷方式放到哪里？
SelectStartMenuFolderLabel3=将在以下开始菜单文件夹中创建快捷方式。
SelectStartMenuFolderBrowseLabel=点击“下一步”继续，或点击“浏览”更改文件夹。
NoProgramGroupCheck2=不创建开始菜单快捷方式(&D)
WizardReady=准备安装
ReadyLabel1=即将在你的电脑上安装 [name]。
ReadyLabel2a=点击“安装”开始，或点击“上一步”更改设置。
ReadyLabel2b=点击“安装”开始安装。
ReadyMemoDir=安装位置：
ReadyMemoGroup=开始菜单文件夹：
ReadyMemoTasks=附加操作：
WizardPreparing=正在准备安装
PreparingDesc=正在准备安装 [name]。
CannotContinue=安装无法继续。请点击“取消”退出。
CloseApplications=自动关闭相关程序(&A)
DontCloseApplications=不关闭相关程序(&D)
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候。
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=[name] 已成功安装。
FinishedLabel=[name] 已成功安装。你可以通过开始菜单或桌面快捷方式打开程序。
ClickFinish=点击“完成”退出安装向导。
FinishedRestartLabel=需要重新启动电脑才能完成安装。是否现在重启？
FinishedRestartMessage=需要重新启动电脑才能完成安装。%n%n是否现在重启？
ShowReadmeCheck=查看使用说明
YesRadio=现在重启(&Y)
NoRadio=稍后重启(&N)
UninstallNotFound=找不到卸载日志文件 %1。
ConfirmUninstall=确认卸载 %1 及其所有程序组件？
UninstallStatusLabel=正在卸载 %1，请稍候。
UninstalledAll=%1 已成功卸载。
UninstalledMost=%1 已卸载。部分文件无法移除，可手动删除。

[CustomMessages]
CreateDesktopIcon=创建桌面快捷方式(&D)
LaunchProgram=打开 %1
